@startuml diagrama_paquetes
' https://plantuml.com/es/

package "vendor" {
  [kint-php/kint]
  [phpunit/phpunit]
  [guzzlehttp/guzzle]
  [monolog/monolog]
  [dompdf/dompdf]
  [twig/twig]
  [symplify/easy-coding-standard]
  [illuminate/database]
  [Autoload] #Yellow
}

package "Entidades" {
  [Juego]
  [Tablero]
  [Palabra]
  [CargarPalabra]
  [ValidarCargarPalabra]
  [Movimiento]
  [ValidarMomiento]
  [TipoMovimiento]
}

package "Controlador" {
  [ControladorJuego]
  [ControladorTablero]
  [ControladorPalabra]
  [ControladorMovimiento]
  [ControladorTipoMovimiento]
}

package "Vista" {
  [VistaJuego]
  [TableroTablero]
  [VistaPalabra]
  [VistaMovimiento]
  [VistaTipoMovimiento]
}




database "Postgres" {
    frame "sopa de letras" {
        [SopaDeLetras]
    }
}


[ControladorJuego] -left-> [Autoload]
[ControladorJuego] -right-> [Juego]
[ControladorJuego] -right-> [VistaJuego]
[illuminate/database] -up-> [SopaDeLetras]

@enduml